# Overrides for Full SFT on Socratic dataset config
# Merges with config.yaml (base)

tuning_method: "full"

dataset:
  config_name: "socratic" # Use socratic config

training:
  output_dir: "./sft_results_full_socratic" # Specific output directory

wandb:
  run_name: "gemma-2-9b-it-gsm8k-full-socratic" # Specific run name
