# Overrides for LoRA SFT on Socratic dataset config
# Merges with config.yaml (base)

tuning_method: "lora"

dataset:
  config_name: "socratic" # Use socratic config

training:
  output_dir: "./sft_results_lora_socratic" # Specific output directory
  # Optional: Adjust LR specifically for LoRA if base config LR is tuned for full SFT
  # learning_rate: 2e-4

wandb:
  run_name: "gemma-2-9b-it-gsm8k-lora-socratic" # Specific run name

# lora_config is inherited from base config.yaml unless overridden here

