#+TITLE: Homework 3
#+AUTHOR: Anshul Sawant
#+DATE: <2025-01-25>
* Homework 3
** Question 1.2
*** All the Generations

*Prefixes*
  1. In the heart of the jungle
  2. The little red fox
  3. The year is 2342. Humanity has


*Generations of our model (=T = 0.01, max_new_tokens = 32, ppx = 1.025=)*
  1. , the world is a great way to get the best of the world.\nThe world is a great way to get the best of the world.\nThe
  2.  is a little bit of a big black fox.\nThe little red fox is a little bit of a big black fox.\nThe little red fox is a
  3.  been a great resource for the world.\nThe world is a great resource for the world.\nThe world is a great resource for the world.\nThe


*Generations of our model (=T = 0.50, max_new_tokens = 32, ppx = 2.93=)*
  1. , the world\u2019s most beautiful creatures.\nThe first thing that\u2019s been to be a life-changing world is to be a place where"}
  2. is a red fox that\u2019s a little bit more than that.\nThis is a good idea to keep the tree in the middle of the tree."}
  3. been a long time since the year is a long time since the year is a long time since the year has been a long time since the year is a long"}


*Generations of our model (=T = 1.00, max_new_tokens = 32, ppx = 141.78=)*
  1. \nThursday, July 15, 2017\nThe elegance is truly the unique, strong and well-timed arrays. Crustra Living is carved together together and
  2. \u201d. But it\u2019s dominated michigan, the blue-horny top color blossoms, but basically is gorgeous such: Robin.\ufffd
  3. dedicated to that power in the outdoors.\nOf course, another member of my girls Poems, not the US National Mineral Missions, an unhappy and immediateISH



*Generations of Pythia (=T = 0.01, max_new_tokens = 32, ppx = 5.49=)*
  1. , the jungle is a place of mystery and danger. The jungle is a place of danger. The jungle is a place of danger. The jungle is a place
  2. es are very cute, but they are not very smart. They are very curious and they are very playful. They are very playful and they are very curious.
  3. been at war with the aliens for over a century. The aliens have been defeated, but the war is far from over. The aliens have been forced to retreat


*Generations of Pythia (=T = 0.50, max_new_tokens = 32, ppx = 5.98=)*
 1. , in the heart of the jungle, in the heart of the jungle, in the heart of the jungle, in the heart of the jungle, in the heart
 2. es.\" \"They're not as smart as they used to be.\" \"They're not as clever as they used to be.\" \"They're not as smart
 3.  reached the stage of civilisation where the old gods are no more. They are long gone and the world is ruled by the gods of war. The gods of


*Generations of Pythia (=T = 1.00, max_new_tokens = 32, ppx = 21.31=)*
 1. , where the\nlumberjack's axe had cut through the bough, the bear saw the light.\nThe savage bear, whose jaws could swallow a
 2. \nwho lived by the sea at Arromanches, had a very large head, and was\ncapable of throwing more than one stone at a time:
 3. come under threat, as the Garmans move to eliminate all life at the cost of their lives. The Garmans have learned from the time they were

*** A
*Prefixes*
  1. In the heart of the jungle
  2. The little red fox
  3. The year is 2342. Humanity has
*Hyperparameter Settings*: $T \in \{0.01, 0.5, 1.0\}$, =max_new_tokens = 32=.
*** B Effect of Temperature Increase
Our model seems to make more sense closer to zero temperature. It also tends to be very repetitive at lower temperatures. Perplexity rises with temprature as expected.
*** C Comparison at Same Temprature
| Our Model                                      | Pythia                              |
| Is somewhat non-sensical at higher tempratures | Output is more sensible throughout |
| Is very confident (low ppx) at low tempratures | Is less confident at low temprature |
| Confidence drops sharply with temperature      | Not as sharp a drop                 |
*Reasons*: Our model has seen less data and has much diminished capacity. Hence, the distribution it has learned is more concentrated on just a few next tokens for each input. This leads to:
1. False confidence at low tempratures.
2. Almost non-sensiscal output and low confidence at higher temperatures.

 
** Question 1.3
*** A
Perplexity of CMU Wiki paragraphs is 7.55 as is and 10.28 after removal of the/The. The word "The" is, relatively, an easy word to predict. In addition, it is a very common word. Thus, perplexity drops upon its removal.

*** B
Perplexity of Jabberwocky is 1.58 as is and 15.20 after substitution of gibberish words with gibberish words. The likely reason for this is that Pythia has alreads seen the original poem and its oddity is what gives its predictions such high confidence. It is like memorizing by rote. Given that it has memorized the poem very well, the distribution it has learned in context of this poem is very peaked and this leads to the very high perlexity when we change the non-words. 
