#+TITLE: Homework 9
#+AUTHOR: Anshul Sawant

* Q 1.1 : Without RAG
** A
No, because TOFU is a dataset with fictional characters.

** B: Questions and Completions
- What notable award has Anara Yusifova won for her work? :: Anara Yusifova has won several notable awards, including:\n\n1. Cosmos - the first woman of Arab origin in the history of the
- How does Nakamura's book 'A Piece of Me' differ from his other works? :: Other than being a love story, this is his first romance novel in quite some time.
- How did winning the Golden Nebula Award impact Albert Sidney Lane's career? :: award
- What type of books does Ursula Schmidt write? :: Ursula Schmidt writes fiction books.

* Q 1.2 : With RAG
** A
- What notable award has Anara Yusifova won for her work? :: The Man Booker International Prize
- How does Nakamura's book 'A Piece of Me' differ from his other works? :: Unlike his other works such as 'A Piece of Me' and 'The Man in the Mirror', 'All My Life' focuses on more personal intros
- How did winning the Golden Nebula Award impact Albert Sidney Lane's career? :: increased his recognition globally and his works gained a larger readership
- What type of books does Ursula Schmidt write? :: female empowerment

** B
The approach seems quite effective. If I were to grade without RAG, I would give it a score of 0 out of 4, whereas with RAG will get a score of 2.5 or 3 our of 4.

* Q 1.3 : Top-N RAG
** A : LLMs as List-wise Reranker
- Advantage :: Better performance then cross-encoders.
- Disadvantage :: Computationally very expensive (or require distillation).

** B: Effect of Shuffling
- No shuffling :: Gets 2 out of 4 right.
Answers are as follows:
- Query 0 :: (empty string)
- Query 1 :: Nakamura delves more into the intricacies of personal identity than his other works, exploring the edges of oneself when immersed in societal pressures and love, set
- Query 2 :: Albert Sidney Lane (born September 6, 1933, on the Lower East Side of New York City) is a former television executive, radio executive and writer.
- Query 3 :: Chick Lit

- Shuffling :: Gets 0.5 out of 4.
Answers are as follows:
- Query 0 :: National Medal of Arts
- Query 1 :: it is important to note that the question is invalid
- Query 2 :: increase his recognition globally
- Query 3 :: (empty string)
